version: "3.8"
networks:
  _:
    name: "$network"
services:
  caddy:
    build:
      context: "."
      dockerfile: "Caddy.dockerfile"
    command: "caddy run --adapter caddyfile --config /conf/${caddyenv}.caddyfile"
    env_file: ".env"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:2019:2019"
    volumes:
      - "./data:/data/caddy:rw"
      - "./logs:/logs/caddy:rw"
      - "./tls:/tls:ro"
      - "./config:/conf:ro"
    networks:
      _: {}
